CREATE TABLE `sys_station` (
  `station_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '站点id',
  `unit_code` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '供电公司id',
  `station_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '站点编码',
  `station_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '站点名称',
  `short_name` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '站点简称',
  `phone_num` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '物联网卡号',
  `hardware_version` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '硬件版本号',
  `longitude` decimal(10,7) DEFAULT '0.0000000' COMMENT '经度',
  `latitude` decimal(10,7) DEFAULT '0.0000000' COMMENT '纬度',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '详细地址',
  `introduction` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '站点介绍',
  `station_img` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '站点图片',
  `region_id` bigint(20) DEFAULT NULL COMMENT '行政区域id',
  `maintenance_id` bigint(20) DEFAULT NULL COMMENT '管理区域id',
  `leader` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '负责人',
  `phone` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系电话',
  `commission_date` datetime DEFAULT NULL COMMENT '投运时间',
  `station_type` int(1) DEFAULT '0' COMMENT '变电站类型（0电厂、1变电站）',
  `status` int(1) DEFAULT '0' COMMENT '激活状态（0=已拆除,1=已停用,2=在运行）',
  `order_num` int(5) DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '备注',
  `del_flag` int(1) DEFAULT '0' COMMENT '删除标志（0=存在,2=删除）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新者',
  `region_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '行政区域名称',
  `pms_subs_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'PMS变电站标识',
  `inline_id` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变电站入线的标识',
  `mt_cap` int(10) DEFAULT NULL COMMENT '主变容量',
  `mt_num` int(5) DEFAULT NULL COMMENT '主变台数',
  `subs_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '用采主站中站点编码',
  PRIMARY KEY (`station_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10452 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='变电站';



CREATE TABLE `maintenance_pool` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '运维池记录id',
  `region_id` bigint(20) NOT NULL COMMENT '行政区域id',
  `station_id` bigint(20) NOT NULL COMMENT '站点id',
  `station_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '站点名称',
  `station_code` bigint(20) NOT NULL COMMENT '站点编号',
  `position_id` bigint(20) NOT NULL COMMENT '线路id',
  `position_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '线路名称',
  `position_num` int(5) NOT NULL COMMENT '线路位置',
  `transformer_id` bigint(20) NOT NULL COMMENT '互感器id',
  `voltage_level` int(1) DEFAULT NULL COMMENT '线路电压',
  `transformer_type` int(1) NOT NULL DEFAULT '4' COMMENT '互感器类型（1=ct,1=vt,2=cvvt,4=cvt,5=ect,6=evt）',
  `factory_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '厂家',
  `model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '型号',
  `phase_sequence` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相序(A=a相,B=b相,C=c相)',
  `evaluation_value` decimal(10,5) NOT NULL COMMENT '评估值',
  `monitior_state` int(1) NOT NULL COMMENT '监控状态(0正常、1警告、2异常）',
  `test_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '检测时间（工单创建时间）',
  `order_status` int(1) NOT NULL DEFAULT '0' COMMENT '工单状态（0未完成，1完成）',
  `audit_status` int(1) NOT NULL DEFAULT '0' COMMENT '是否审核(0未审核，1已审核，2已处理)',
  `order_id` bigint(20) DEFAULT NULL COMMENT '工单id',
  `region_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '行政区域名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='运维池';


CREATE TABLE `maintenance_order` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '工单id',
  `station_id` bigint(20) NOT NULL COMMENT '站点id',
  `station_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '站点编号',
  `station_name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '站点名称',
  `position_id` bigint(20) NOT NULL COMMENT '线路id ',
  `position_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '线路名称',
  `position_num` int(2) NOT NULL COMMENT '线路位置',
  `transformer_id` bigint(20) NOT NULL COMMENT '互感器id',
  `region_id` bigint(20) DEFAULT NULL COMMENT '行政区域id',
  `maintenance_id` bigint(20) DEFAULT NULL COMMENT '管理区域id',
  `company_user_id` bigint(20) DEFAULT NULL COMMENT '运维用户ID',
  `order_status` int(1) NOT NULL DEFAULT '0' COMMENT '工单状态（0未派单、1待确认、2已确认、3已完成）',
  `evaluation_value` decimal(8,5) DEFAULT NULL COMMENT '评估值',
  `blackout_plan_id` bigint(20) DEFAULT NULL COMMENT '停电计划id',
  `appraisal_value` decimal(8,5) NOT NULL COMMENT '鉴定值',
  `repair_time` datetime DEFAULT NULL COMMENT '检修时间',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `phase_sequence` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '相序(A=a相,B=b相,C=c相)',
  `order_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '工单编号',
  `monitior_state` int(1) NOT NULL COMMENT '监控状态(0正常、1警告、2异常）',
  `region_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '行政区域名称',
  `blackout_plan_status` int(1) DEFAULT '1' COMMENT '停电计划(0有停电计划,1无停电计划)',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='运维工单';